name: Continuous Integration (prod)

on:
  pull_request:
    branches: [ "main", "release" ]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: false

permissions:
  contents: read

jobs:
  production-test:
    runs-on: ubuntu-22.04
    env:
      REPO: ${{ secrets.DOCKER_REPOSITORY }}

    steps:
      - name: Checkout PR
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up App configuration
        run: |
          echo "${{ secrets.APPLICATION_TEST }}" > ./src/test/resources/application-test.yml
        shell: bash

      - name: Create Json
        uses: jsdaniell/create-json@v1.2.2
        with:
          name: "./src/test/resources/firebase-config.json"
          json: ${{ secrets.FIREBASE_PROD_JSON }}

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Test App
        run: ./gradlew clean test --stacktrace


      - name: Send Slack message
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
          if_mention: failure,cancelled
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_BACKEND_TEAM_URL }} # required
        if: always() # Pick up events even if the job fails or is canceled.
